# Generated by Django 3.2.16 on 2022-11-29 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deskbooking', '0002_alter_booking_desk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='desk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='desk_booking', to='deskbooking.desk'),
        ),
    ]
